import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const checkOnly = process.argv.includes("--check");
const release = JSON.parse(readFileSync(resolve(root, "release/release.json"), "utf8"));

if (!/^\d+\.\d+\.\d+$/.test(release.version)) throw new Error("release version must be SemVer x.y.z");
if (!["Development", "Beta", "Stable"].includes(release.channel)) throw new Error("invalid release channel");
if (!Number.isSafeInteger(release.schemaVersion) || release.schemaVersion < 1) throw new Error("invalid schema version");

const mismatches = [];
function replaceRequired(text, pattern, replacement, label) {
  if (!pattern.test(text)) throw new Error(`release target not found: ${label}`);
  return text.replace(pattern, replacement);
}
function syncText(relativePath, transform) {
  const path = resolve(root, relativePath);
  const before = readFileSync(path, "utf8");
  const after = transform(before);
  if (before === after) return;
  if (checkOnly) mismatches.push(relativePath);
  else writeFileSync(path, after, "utf8");
}

for (const path of ["package.json", "apps/desktop/package.json", "apps/mobile/package.json", "packages/core/package.json"]) {
  syncText(path, (text) => {
    const json = JSON.parse(text);
    json.version = release.version;
    return `${JSON.stringify(json, null, 2)}\n`;
  });
}

syncText("apps/desktop/src-tauri/tauri.conf.json", (text) => {
  const json = JSON.parse(text);
  json.version = release.version;
  return `${JSON.stringify(json, null, 2)}\n`;
});
syncText("apps/mobile/app.json", (text) => {
  const json = JSON.parse(text);
  json.expo.version = release.version;
  return `${JSON.stringify(json, null, 2)}\n`;
});

syncText("apps/desktop/src-tauri/Cargo.toml", (text) =>
  replaceRequired(text, /(\[package\][\s\S]*?\nversion\s*=\s*)"[^"]+"/, `$1"${release.version}"`, "Cargo.toml package version"),
);
syncText("apps/desktop/src-tauri/Cargo.lock", (text) =>
  replaceRequired(text, /(name = "mep-finance-desktop"\r?\nversion = )"[^"]+"/, `$1"${release.version}"`, "Cargo.lock package version"),
);
syncText("apps/desktop/src-tauri/src/lib.rs", (text) =>
  replaceRequired(
    text,
    /const CURRENT_SCHEMA_VERSION: i64 = \d+;/,
    `const CURRENT_SCHEMA_VERSION: i64 = ${release.schemaVersion};`,
    "Rust schema version",
  ),
);

const generated = `// Generated by scripts/sync-version.mjs from release/release.json. Do not edit.\n` +
  `export const APP_VERSION = ${JSON.stringify(release.version)};\n` +
  `export const RELEASE_CHANNEL = ${JSON.stringify(release.channel)} as "Development" | "Beta" | "Stable";\n` +
  `export const EXPECTED_SCHEMA_VERSION = ${release.schemaVersion};\n`;
syncText("apps/desktop/src/generated/release.ts", () => generated);
syncText("apps/mobile/src/generated/release.ts", () => generated);

const changelog = readFileSync(resolve(root, "CHANGELOG.md"), "utf8");
if (!changelog.includes(`## [${release.version}]`)) mismatches.push("CHANGELOG.md");

if (mismatches.length) {
  throw new Error(`release metadata is out of sync: ${[...new Set(mismatches)].join(", ")}. Run pnpm version:sync.`);
}

console.log(`NAMAA Finance ${release.version} (${release.channel}), schema ${release.schemaVersion}: ${checkOnly ? "verified" : "synchronized"}`);
